I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 86, in script
    s "Oh, es ist schon so spät, ich sollte mich besser beeilen...Aber der Tag ist so schön.."
  File "game/script.rpy", line 86, in script
    s "Oh, es ist schon so spät, ich sollte mich besser beeilen...Aber der Tag ist so schön.."
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'horn_big.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 86, in script
    s "Oh, es ist schon so spät, ich sollte mich besser beeilen...Aber der Tag ist so schön.."
  File "game/script.rpy", line 86, in script
    s "Oh, es ist schon so spät, ich sollte mich besser beeilen...Aber der Tag ist so schön.."
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/ast.py", line 689, in execute
    statement_name(stmt_name)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/ast.py", line 46, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/display/core.py", line 2752, in do_with
    clear=clear)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/display/core.py", line 4020, in interact_core
    renpy.audio.audio.periodic()
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "/home/towa/Downloads/renpy-7.4.10-sdk/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'horn_big.wav'.

Linux-5.4.0-91-generic-x86_64-with-debian-buster-sid
Ren'Py 7.4.10.2178
Der Besuch der alten Dame 1.0
Tue Dec  7 21:10:47 2021
